spring.application.name=ScattergoriesTogetherAPI
debug = true
mongodb+srv://mgilchrist:NHLRulz16!@scattergoriestogether.m1nxu.mongodb.net/scattegories?retryWrites=true&w=majority&appName=ScattergoriesTogether
server.port=${SERVER_PORT:8080}